# Generated by Django 3.2.3 on 2023-07-24 11:52

from django.db import migrations

import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230720_1528'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', user.models.NewUserManager()),
            ],
        ),
    ]
