# Generated by Django 3.2.3 on 2023-09-02 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='subscribed_to',
            field=models.ManyToManyField(through='user.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
